/* MTI_DPI */

/*
 * Copyright 2002-2014 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux'
 */
#ifndef INCLUDED_TBXBINDINGS
#define INCLUDED_TBXBINDINGS

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
GetInstrFmMem(
    const svBitVecVal* instr,
    const svBitVecVal* PC);

DPI_LINK_DECL DPI_DLLESPEC
int
OperationComplete();

DPI_LINK_DECL DPI_DLLESPEC
int
ResetOpr();

DPI_LINK_DECL DPI_DLLESPEC
int
SendResOfProc(
    svBit* ResultOfOprFlg);

#endif 
